[build-system]
requires = ["setuptools>=61.0", "pybind11>=2.12"]
build-backend = "setuptools.build_meta"

[project]
name = "boid_engine"
version = "0.1.0"
dependencies = [
    "pygame==2.6.1",
    "numpy==2.4.2",
    "psutil==7.2.2",
]